---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Gather the package facts
    package_facts:
     manager: auto
#  - name: Print the package facts
#    debug:
#      var: ansible_facts.packages
  - name: Verify package vim is installed
    assert:
      that:
        - "'vim-common' in ansible_facts.packages"
      fail_msg: "'vim' package isn't installed"
      success_msg: "'vim' package is succesfully installed"
